// ------------------------------------------------------------------
// © Copyright 2017 Thermo Fisher Scientific Inc. All rights reserved.
// ------------------------------------------------------------------
using System;

namespace Thermo.Kronos.Instrument.Camera.Contracts.Data
{
    /// <summary></summary>
    [Serializable]
    public class CameraSubarraySettings
    {
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Subarray Id number.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the analyte id.
        /// </summary>
        public Guid AnalyteId { get; set; }

        /// <summary>
        /// Gets or sets the region.
        /// </summary>
        public CameraRegion Region { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [read enabled].
        /// </summary>
        public bool ReadEnabled { get; set; }

        /// <summary>
        /// Gets or sets the read interval.
        /// </summary>
        public int ReadInterval { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [sub inject enabled].
        /// </summary>
        public bool SubInjectEnabled { get; set; }

        /// <summary>
        /// Gets or sets the sub inject interval.
        /// </summary>
        public int SubInjectInterval { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [post read enabled].
        /// </summary>
        public bool PostReadEnabled { get; set; }

        /// <summary>
        /// Gets or sets the post read non destructive reads.
        /// </summary>
        public int PostReadNonDestructiveReadouts { get; set; }

        /// <summary>
        /// Gets or sets the subarray FixedPatternNoiseReduction.
        /// </summary>
        public int SubarrayFixedPatternNoiseReduction { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [treshold enabled].
        /// </summary>
        public bool TresholdEnabled { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [time resolved enabled].
        /// </summary>
        public bool TimeResolvedEnabled { get; set; }

        /// <summary>
        /// Gets or sets the Time Resolved interval.
        /// </summary>
        public int TimeResolvedInterval { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [adaptive enabled].
        /// </summary>
        public bool AdaptiveEnabled { get; set; }

        /// <summary>
        /// Gets or sets the treshold value percentage.
        /// </summary>
        public short TresholdValuePercentage { get; set; }

        /// <summary>
        /// Gets or sets the treshold region.
        /// </summary>
        public CameraRegion TresholdRegion { get; set; }

        /// <summary>
        /// Gets or sets a field whether the Subarray Id is supplied by operator or autogenerated.
        /// </summary>
        public bool SubarrayIdSupplied { get; set; }
    }
}