//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KronosCameraTestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1431")]
        public int FormWidth {
            get {
                return ((int)(this["FormWidth"]));
            }
            set {
                this["FormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("832")]
        public int FormHeight {
            get {
                return ((int)(this["FormHeight"]));
            }
            set {
                this["FormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.8")]
        public float selectInjectVb {
            get {
                return ((float)(this["selectInjectVb"]));
            }
            set {
                this["selectInjectVb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float selectInjectVc {
            get {
                return ((float)(this["selectInjectVc"]));
            }
            set {
                this["selectInjectVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.8")]
        public float selectInjectVd {
            get {
                return ((float)(this["selectInjectVd"]));
            }
            set {
                this["selectInjectVd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.75")]
        public float selectSenseVa {
            get {
                return ((float)(this["selectSenseVa"]));
            }
            set {
                this["selectSenseVa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.75")]
        public float selectSenseVb {
            get {
                return ((float)(this["selectSenseVb"]));
            }
            set {
                this["selectSenseVb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public float selectSenseVc {
            get {
                return ((float)(this["selectSenseVc"]));
            }
            set {
                this["selectSenseVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float selectStoreVa {
            get {
                return ((float)(this["selectStoreVa"]));
            }
            set {
                this["selectStoreVa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float selectStoreVb {
            get {
                return ((float)(this["selectStoreVb"]));
            }
            set {
                this["selectStoreVb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float selectStoreVc {
            get {
                return ((float)(this["selectStoreVc"]));
            }
            set {
                this["selectStoreVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.05")]
        public float transferSel {
            get {
                return ((float)(this["transferSel"]));
            }
            set {
                this["transferSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.9")]
        public float videoBias {
            get {
                return ((float)(this["videoBias"]));
            }
            set {
                this["videoBias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.2")]
        public float pixelVdd {
            get {
                return ((float)(this["pixelVdd"]));
            }
            set {
                this["pixelVdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float cdsRef {
            get {
                return ((float)(this["cdsRef"]));
            }
            set {
                this["cdsRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float offset {
            get {
                return ((float)(this["offset"]));
            }
            set {
                this["offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float gain {
            get {
                return ((float)(this["gain"]));
            }
            set {
                this["gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float impxbiasVa {
            get {
                return ((float)(this["impxbiasVa"]));
            }
            set {
                this["impxbiasVa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float selResetVc {
            get {
                return ((float)(this["selResetVc"]));
            }
            set {
                this["selResetVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float outBiasVd {
            get {
                return ((float)(this["outBiasVd"]));
            }
            set {
                this["outBiasVd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Default\"")]
        public string InfraStyleName {
            get {
                return ((string)(this["InfraStyleName"]));
            }
            set {
                this["InfraStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"BABA\"")]
        public string DefaultFilePath {
            get {
                return ((string)(this["DefaultFilePath"]));
            }
            set {
                this["DefaultFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormLocationX {
            get {
                return ((int)(this["FormLocationX"]));
            }
            set {
                this["FormLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormLocationY {
            get {
                return ((int)(this["FormLocationY"]));
            }
            set {
                this["FormLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SCM5821AData\\")]
        public string FilesLocation {
            get {
                return ((string)(this["FilesLocation"]));
            }
            set {
                this["FilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoTestOrder1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoTestOrder1"]));
            }
            set {
                this["AutoTestOrder1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SelectedPreTests {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectedPreTests"]));
            }
            set {
                this["SelectedPreTests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool noneRadioButton {
            get {
                return ((bool)(this["noneRadioButton"]));
            }
            set {
                this["noneRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fileRadioButton {
            get {
                return ((bool)(this["fileRadioButton"]));
            }
            set {
                this["fileRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool consoleRadioButton {
            get {
                return ((bool)(this["consoleRadioButton"]));
            }
            set {
                this["consoleRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool debugRadioButton {
            get {
                return ((bool)(this["debugRadioButton"]));
            }
            set {
                this["debugRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool infoRadioButton {
            get {
                return ((bool)(this["infoRadioButton"]));
            }
            set {
                this["infoRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool warningRadioButton {
            get {
                return ((bool)(this["warningRadioButton"]));
            }
            set {
                this["warningRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool errorRadioButton {
            get {
                return ((bool)(this["errorRadioButton"]));
            }
            set {
                this["errorRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fatalRadioButton {
            get {
                return ((bool)(this["fatalRadioButton"]));
            }
            set {
                this["fatalRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool firmwareLoggingEnabled {
            get {
                return ((bool)(this["firmwareLoggingEnabled"]));
            }
            set {
                this["firmwareLoggingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection selectedGraphPreferencesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["selectedGraphPreferencesList"]));
            }
            set {
                this["selectedGraphPreferencesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int lineWidthOfPlot {
            get {
                return ((int)(this["lineWidthOfPlot"]));
            }
            set {
                this["lineWidthOfPlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color colorOfPlotBackground {
            get {
                return ((global::System.Drawing.Color)(this["colorOfPlotBackground"]));
            }
            set {
                this["colorOfPlotBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotBackgroundColor {
            get {
                return ((bool)(this["plotBackgroundColor"]));
            }
            set {
                this["plotBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float openShutterSpeed {
            get {
                return ((float)(this["openShutterSpeed"]));
            }
            set {
                this["openShutterSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float closeShutterSpeed {
            get {
                return ((float)(this["closeShutterSpeed"]));
            }
            set {
                this["closeShutterSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableOnConnect {
            get {
                return ((bool)(this["enableOnConnect"]));
            }
            set {
                this["enableOnConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TECEnabled {
            get {
                return ((bool)(this["TECEnabled"]));
            }
            set {
                this["TECEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbortAutoTestCheckBox {
            get {
                return ((bool)(this["AbortAutoTestCheckBox"]));
            }
            set {
                this["AbortAutoTestCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoTestResultsServerFilePathFromDB {
            get {
                return ((string)(this["AutoTestResultsServerFilePathFromDB"]));
            }
            set {
                this["AutoTestResultsServerFilePathFromDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.74")]
        public float OffseteADU {
            get {
                return ((float)(this["OffseteADU"]));
            }
            set {
                this["OffseteADU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public float UnSelsenseVc {
            get {
                return ((float)(this["UnSelsenseVc"]));
            }
            set {
                this["UnSelsenseVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float UnSelstoreVc {
            get {
                return ((float)(this["UnSelstoreVc"]));
            }
            set {
                this["UnSelstoreVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.8")]
        public float UnSelinjectVc {
            get {
                return ((float)(this["UnSelinjectVc"]));
            }
            set {
                this["UnSelinjectVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.05")]
        public float UnSeltgVc {
            get {
                return ((float)(this["UnSeltgVc"]));
            }
            set {
                this["UnSeltgVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float UnSelresetVc {
            get {
                return ((float)(this["UnSelresetVc"]));
            }
            set {
                this["UnSelresetVc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"192.168.1.2\"")]
        public string CameraIPAddress {
            get {
                return ((string)(this["CameraIPAddress"]));
            }
            set {
                this["CameraIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"47151\"")]
        public string CameraPortNumber {
            get {
                return ((string)(this["CameraPortNumber"]));
            }
            set {
                this["CameraPortNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendCameraHeartBeat {
            get {
                return ((bool)(this["sendCameraHeartBeat"]));
            }
            set {
                this["sendCameraHeartBeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool dryRunTest {
            get {
                return ((bool)(this["dryRunTest"]));
            }
            set {
                this["dryRunTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string saveTestResultsToNetworkDrive {
            get {
                return ((string)(this["saveTestResultsToNetworkDrive"]));
            }
            set {
                this["saveTestResultsToNetworkDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string TCubePort {
            get {
                return ((string)(this["TCubePort"]));
            }
            set {
                this["TCubePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string BKPowerPort {
            get {
                return ((string)(this["BKPowerPort"]));
            }
            set {
                this["BKPowerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string FlowMeterPort {
            get {
                return ((string)(this["FlowMeterPort"]));
            }
            set {
                this["FlowMeterPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnectEnvStatCOMPorts {
            get {
                return ((bool)(this["AutoConnectEnvStatCOMPorts"]));
            }
            set {
                this["AutoConnectEnvStatCOMPorts"] = value;
            }
        }
    }
}
